services:
  - type: web
    name: telegram-bot
    env: python
    plan: starter  # ← ВОТ ЭТО ВАЖНО, а не "free"
    buildCommand: pip install -r requirements.txt
    startCommand: python 1win.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: "7927368928:AAFwiYztldKI3o6PMQtQWsQdfpVP69yAeUM"
      - key: WEBHOOK_URL
        value: "https://telegram-bot-jxqd.onrender.com/7927368928:AAFwiYztldKI3o6PMQtQWsQdfpVP69yAeUM"

